version: "3.9"
services:
  mysql:
    container_name: soap_db
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file: .env
    hostname: db-soap-service
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - soap-services

volumes:
  mysql:
networks:
  soap-services:
